export const eventButton = document.getElementById("add-event") as HTMLButtonElement;
export const label = document.querySelector("#add-event .header__button--text") as HTMLSpanElement;
export const modal = document.getElementById("modal") as HTMLElement; 
export const overlay = document.querySelector(".overlay") as HTMLDivElement; 
export const closeModalButton = document.getElementById("close") as HTMLSpanElement;
export const endDateCheckbox = document.getElementById("checkbox") as HTMLInputElement;
export const endDateLabel = document.getElementById("endDate-label") as HTMLLabelElement;
export const endDateInput = document.getElementById("endDate") as HTMLInputElement;
export const endDateTimeLabel = document.getElementById("endTimeLabel") as HTMLLabelElement;
export const endDateTimeInput = document.getElementById("endTimeInput") as HTMLInputElement;
export const reminderCheckbox = document.getElementById("reminderCheckbox")as HTMLInputElement; 
export const reminderTime = document.getElementById("reminderTime") as HTMLSelectElement;
export const submitButton = document.getElementById("submit") as HTMLButtonElement;
export const deleteButton = document.getElementById("delete-event") as HTMLButtonElement;
export const endTimeInput = document.querySelector("endTimeInput") as HTMLInputElement;
export const reminderDurationSelect = document.querySelector("reminderTime") as HTMLSelectElement //està repetit